### ISSUE TITLE
How to send X-Identifier header for testing purposes with function call?

### ISSUE THREAD

**Issue by deg0nz** [derhuerst/vbb-client#1]
You wrote that it would be nice to send an `X-Identifier` header with every request for testing purposes [here](https://github.com/derhuerst/vbb-rest/blob/master/docs/index.md).

I would like to do that, but how can I set a header in Node.js when using a function in `vbb-client`? 
Like sending it with `require('vbb-hafas').departures(…)`.

**Comment by derhuerst** [comment]
Should have documented this. [You have to pass an `identifier` property with the query object.](https://github.com/derhuerst/vbb-client/blob/13a700a/index.js#L38)

**Comment by deg0nz** [comment]
Ok, I see. So I just have to add an `identifier` property to the `opt` object in the `client.departures()` function. 

Thank you! I'll use this in future test runs.
