### ISSUE TITLE
Bad Gateway at request 

### ISSUE THREAD

**Issue by basiclaser** [derhuerst/vbb-client#11]
seems like the originating source is dead/ changed (http://vbb.transport.rest/),(https://2.vbb.transport.rest/stations/8012713/departures?results=1)

```
vbb.departures("8012713", {results: 1})
.then(data => {
    ...
})
``` 
results in 
```
UnhandledPromiseRejectionWarning: Error: Bad Gateway
    at request (node_modules/vbb-client/lib/request.js:27:14
```
I couldn't find a new available API, sorry!

**Comment by derhuerst** [comment]
[From`derhuerst/vbb-rest#29` ](https://github.com/derhuerst/vbb-rest/issues/29#issuecomment-410826088):

> Good news everyone!
>
> I have set up a new API: `1.bvg.transport.rest` provides data from the BVG endpoint. It returns almost exactly the same data as `2.vbb.transport.rest`, but in the output format of [`hafas-client@3.0.0-alpha.20`](https://github.com/public-transport/hafas-client/tree/ffc392b66b5f11a94cf6586ceae156ffed396aa8/docs), so you will have to make minor adjustments. Check the docs at [derhuerst/bvg-rest](https://github.com/derhuerst/bvg-rest/blob/master/readme.md)!
>
> Let's see for how long this API will stay up.

You would have to query this API manually.

**Comment by derhuerst** [comment]
We could also fork `vbb-client` into `bvg-client`, which queries the BVG API.

**Comment by derhuerst** [comment]
Please reopen if you have more questions.
