### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by deg0nz** [derhuerst/vbb-client#3]
How can I understand the versioning of this module?

I'm a little bit confused by that. You have some releases to `0.40.0` here on github, but there are also versions `1.0.0` and `2.0.0` in npm.

Can you clarify that a little bit?

Thanks in advance!
Greetings

**Comment by derhuerst** [comment]
npm releases are supposed to be the canonical ones, as they also have the latest release.

This project follows [SemVer](http://semver.org/), `vbb-client@2` queries the new API at `vbb.transport.rest`. `vbb-client@1` still works but I don't maintain it anymore, and it queries the ols API at `transport.rest` wich I will turn off in the comning days.

**Comment by deg0nz** [comment]
Okay, thanks :)
