### ISSUE TITLE
Refused to set unsafe header "user-agent" - web page use

### ISSUE THREAD

**Issue by mbariola** [derhuerst/vbb-client#4]
Maybe I am getting how to use it wrong...

I am using vbb-client on my web page to make a dynamic map of the public transportaton in my surroundings.
However, when I try to use it, I get "Refused to set unsafe header "user-agent" in console and script aborts.

Maybe I am not using it the right way?
It seems I cannot use index.js directly (I get an error) so I used browserify as directed. 

I did npm install vbb-client

then I did browserify trafficmap.js -o bundle.js

then I included in a script tag bundle.js

Result: Refused to set unsafe header "user-agent"
By looking at code, I see that vbb-client tries to set its own user agent.
I'll attach my very simple js so maybe some glaring error might be spotted ...

`var vbbclient = require('vbb-client');
        window.onload = function() {
            var map = L.map('map').setView([52.457725, 13.540240], 13);

            L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
                attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
            }).addTo(map);

            L.marker([52.457725, 13.540240]).addTo(map)
                .bindPopup('Essentis Eco Hotel')
                .openPopup();
            map.on('moveend', function() { 
                console.log(map.getBounds());

            });
            vbbclient.stations({id: '900000181505'}).then(function (result) {
  console.log('Response from the endpoint ' + result)
}, function (error){
  console.log('An error occurred: ' + error)
});
        };`

**Comment by derhuerst** [comment]
Hey @mbariola,

> Maybe I am getting how to use it wrong...

Doesn't look like it.

> However, when I try to use it, I get "Refused to set unsafe header "user-agent" in console and script aborts.

This happens because in the browser, `fetch()` is not allowed to set a custom user agent. This only works in Node.js. The `vbb-client` tries to work in both though, and to see what people use `vbb-client` for, I set the user agent. However, **it does not cause the `vbb-client` call to fail**, it is only a warning being shown in the terminal.

> It seems I cannot use index.js directly (I get an error) so I used browserify as directed.

That's the correct way to do it.

Did you get a result back eventually?

**Comment by mbariola** [comment]
Hey, thanks for the quick response
No, I wasn't able to. I commented out the user - agent line and hard-coded
my x-identifier and I got a successful promise with an empty body.
When directly calling fetch, and passing the query string as I'd do from my
server, I get back the streamable data

**Comment by derhuerst** [comment]
that is really weird. can you provide the stack trace you get via `.catch()`?

> No, I wasn't able to. I commented out the user - agent line and hard-coded
my x-identifier and I got a successful promise with an empty body.

Which browser do you use?

**Comment by mbariola** [comment]
hey @derhuerst , sorry, was AFK. 

> Which browser do you use?
Browser is Chrome latest running on Windows 10. Server is serving the page from a local LAN IP (192.x)

> that is really weird. can you provide the stack trace you get via .catch()?

That's the funny thing, unless I am missing something really obvious, I have no catch results .. here's the current version of code. maybe you can see in the logs if there's some Test-WebClient-2 X-Identifier?
`
var vbbclient = require('vbb-client');
        window.onload = function() {
            var map = L.map('map').setView([52.457725, 13.540240], 13);

            L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
                attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
            }).addTo(map);

            L.marker([52.457725, 13.540240]).addTo(map)
                .bindPopup('Essentis Eco Hotel')
                .openPopup();
            map.on('moveend', function() { 
                console.log(map.getBounds());
            });
            vbbclient.stations({id: 900000181505, identifier: "Test-WebClient-2"})
                .then(function (result) {
                    console.log('Response from the endpoint ' + result)}
                , function (error){
                    console.log('An error occurred: ' + error)})
                    .catch(function (error){
                        console.log('Aha! Error');
                        console.log(error);
                    });
        };

`

**Comment by derhuerst** [comment]
There's one more reason I can imagine why you don't see the errors/data: Check the filter of your browsers' dev console.

**Comment by mbariola** [comment]
Hello,

I tried to show everything putting it on "verbose" level, but no errors came out. 

If you like, I attached the whole zip of the folder, just run transport.php, maybe you'll be able to see the cause better than I
[html.zip](https://github.com/derhuerst/vbb-client/files/1290345/html.zip)
.

**Comment by derhuerst** [comment]
> If you like, I attached the whole zip of the folder

Your zip does not contain the `package.json` file. Nevertheless, It looks like you installed the latest version of `vbb-client`.

> just run `transport.php`

I don't have PHP set up on my machine.

BTW you should probably change your API key, because your zip file contains it.

**Comment by mbariola** [comment]
that's what happens when just woken up, I was sure I had removed all inessential files, thanks for the heads up
here goes w/ transport.html - no php in it
[html.zip](https://github.com/derhuerst/vbb-client/files/1290455/html.zip)

**Comment by derhuerst** [comment]
Sorry, totally missed two issues:

- You're querying `/stations` from the API with an `id` parameter, which will be ignored. [If you want to search for stations by name, pass a `query` parameter.](https://github.com/derhuerst/vbb-rest/blob/master/docs/index.md#get-stationsquery) [If you want to get data on a single station, use `.station(id)`.](https://github.com/derhuerst/vbb-rest/blob/master/docs/index.md#get-stationsid) [If you want to get departures at a station, use `.departures(id)`.](https://github.com/derhuerst/vbb-rest/blob/master/docs/index.md#get-stationsiddepartures)
- In the `.then()` function, you're concatenating your string `'Response from the endpoint '` with `result`. Because, in your specific case, `result` is an empty array, it gets converted to an empty string. You should therefore see just `Response from the endpoint ` in the dev tools console. `console.log` supports any number of arguments, so log like this: `console.log('response', result)`.

**Comment by derhuerst** [comment]
I will clarify the docs here in `vbb-client`.

**Comment by mbariola** [comment]
Thanks, I see I was including the id in the object and not outside of it, now I fixed it and it works, you might see the x-Identifier too . Thanks for the tip re console.log too, I'm more of a backend guy :-)

**Comment by derhuerst** [comment]
FYI `vbb-client` will work on the server side just like you used it in the browser now. Also, you won't get a warning about the `user-agent` header.
