### ISSUE TITLE
cache: 'no-store',

### ISSUE THREAD

**Issue by jfilter** [derhuerst/vbb-client#5]
cache: 'no-store',

I think you should always enforce this caching. We always want to have the latest data.

**Comment by derhuerst** [comment]
The API sends a [`Cache-Control` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) looking as follows if appropriate, so this should not be necessary.

```
Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate
Pragma: no-cache
ETag: W/"346d-Ojbr4+ucNw/GhCHOR+qsfMbfUkw"
```

Is there a particular case where this didn't work for you?

**Comment by derhuerst** [comment]
Please reopen if you encounter this issue again.

**Comment by derhuerst** [comment]
From what I can tell reading [`no-store` vs `no-cache`](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching#no-cache_and_no-store), only `no-cache` should be present, not `no-store`.
