### ISSUE TITLE
GET /stations/all not implemented yet?

### ISSUE THREAD

**Issue by patrickj0607** [derhuerst/vbb-client#6]
While playing around with ``vbb-client`` by using the methods described in the [API Section](https://github.com/derhuerst/vbb-client#api) of [readme.md](../blob/master/readme.md), I noticed that ``allStations()`` does not work. As I could not find anything in [index.js](../blob/master/index.js), am I correctly assuming that it is not implemented yet?

P.S. Thanks a lot for your great work!

**Comment by derhuerst** [comment]
FYI the `/stations/all` route is documented [here](https://github.com/derhuerst/vbb-rest/blob/a22e8f5bdb18d2224c7206813cc2ef7368b1d733/docs/index.md#get-stationsall). And it works:

```shell
curl 'https://2.vbb.transport.rest/stations/all'
```

**But you're right, `allStations()` is not implemented.**
