### ISSUE TITLE
Parameters name, address in GET /journeys

### ISSUE THREAD

**Issue by patrickj0607** [derhuerst/vbb-client#7]
As the POI/address format requires ``latitude`` and ``longitude`` parameter values, could you kindly explain me the sense of supplying additionally parameter values for ```name``` and ```address```. Thank you!

Code example:
``` 
vbb.journeys('900000003201', {
    type: 'location',
    name: 'Joe\'s place', 
    address: 'Torfstraße 17', 
    latitude: 52.5416823, longitude: 13.3491223
  })
.then(console.log)
.catch(console.error)
```

**Comment by derhuerst** [comment]
[`hafas-client`](https://github.com/public-transport/hafas-client) (and therefore [`vbb-hafas`](https://github.com/derhuerst/vbb-hafas), and therefore [`vbb-rest`](https://github.com/derhuerst/vbb-rest)) returns data in the [*Friendly Public Transport Format* `1.0.1`](https://github.com/public-transport/friendly-public-transport-format/blob/1.0.1/spec/readme.md).

The HAFAS endpoint being queried distinguishes **stations, POIs and addresses**. Therefore `hafas-client` needs to know what *kind* of "thing" you're passing in. The specific format for these can been in [the `journeys()` docs](https://github.com/public-transport/hafas-client/blob/master/docs/journeys.md#journeysfrom-to-opt).
